headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[dev]
command = "node server.js"
port = 3000.0
publish = "public"

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\mishr\\Desktop\\video proctoring system\\public"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'No build step required - static files ready'"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "*.js"

[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.css"

[headers.values]
Cache-Control = "public, max-age=31536000"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]