const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');

const htmlTemplate = `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Proctoring Report</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; margin: 0; padding: 20px; color: #333; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #4a6fa5; padding-bottom: 10px; }
        .header h1 { color: #2c3e50; margin: 0; }
        .info { margin-bottom: 20px; }
        .info p { margin: 5px 0; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .summary { margin: 20px 0; padding: 15px; background-color: #f9f9f9; border-left: 4px solid #4a6fa5; }
        .footer { margin-top: 30px; font-size: 12px; text-align: center; color: #777; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Video Proctoring Report</h1>
        <p>Generated on: ${new Date().toLocaleString()}</p>
    </div>
    
    <div class="info">
        <h2>Exam Information</h2>
        <p><strong>Candidate ID:</strong> CAN-2023-001</p>
        <p><strong>Exam Name:</strong> Sample Certification Exam</p>
        <p><strong>Date:</strong> September 16, 2025</p>
        <p><strong>Duration:</strong> 30 minutes</p>
    </div>
    
    <div class="summary">
        <h3>Integrity Summary</h3>
        <p><strong>Overall Integrity Score:</strong> 85/100</p>
        <p><strong>Status:</strong> Passed with Minor Concerns</p>
        <p><strong>Total Warnings:</strong> 4</p>
        <p><strong>Critical Issues:</strong> 1</p>
    </div>
    
    <h3>Detailed Activity Log</h3>
    <table>
        <thead>
            <tr>
                <th>Time</th>
                <th>Event</th>
                <th>Severity</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>10:00:05</td>
                <td>Face Detected</td>
                <td>Info</td>
                <td>Primary face detected</td>
            </tr>
            <tr>
                <td>10:02:15</td>
                <td>Face Not Detected</td>
                <td>Warning</td>
                <td>No face detected for 3 seconds</td>
            </tr>
            <tr>
                <td>10:05:30</td>
                <td>Multiple Faces</td>
                <td>Warning</td>
                <td>2 faces detected simultaneously</td>
            </tr>
            <tr>
                <td>10:08:45</td>
                <td>Gaze Direction</td>
                <td>Warning</td>
                <td>Candidate looked away from screen</td>
            </tr>
            <tr>
                <td>10:10:20</td>
                <td>Object Detected</td>
                <td>High</td>
                <td>Mobile phone detected on desk</td>
            </tr>
            <tr>
                <td>10:15:22</td>
                <td>Audio Detected</td>
                <td>Warning</td>
                <td>Audio input detected during exam</td>
            </tr>
            <tr>
                <td>10:18:40</td>
                <td>Window Focus Lost</td>
                <td>High</td>
                <td>Browser tab focus lost for 2 seconds</td>
            </tr>
            <tr>
                <td>10:22:30</td>
                <td>Test Completed</td>
                <td>Info</td>
                <td>Exam session completed successfully</td>
            </tr>
        </tbody>
    </table>
    
    <div class="footer">
        <p>This report was automatically generated by the Video Proctoring System.</p>
        <p>© 2025 Video Proctoring System. All rights reserved.</p>
    </div>
</body>
</html>
`;

async function generatePDF() {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    
    // Set the HTML content
    await page.setContent(htmlTemplate, {
        waitUntil: 'networkidle0'
    });
    
    // Generate PDF
    const pdfPath = path.join(__dirname, 'sample_proctoring_report.pdf');
    await page.pdf({
        path: pdfPath,
        format: 'A4',
        printBackground: true,
        margin: {
            top: '20mm',
            right: '15mm',
            bottom: '20mm',
            left: '15mm'
        }
    });
    
    console.log(`PDF generated at: ${pdfPath}`);
    await browser.close();
}

generatePDF().catch(console.error);
